tooling/charts/do500/templates/docs/deploy.yaml, tooling/charts/do500/templates/docs/routes.yaml, tooling/charts/do500/templates/gitlab/anyuid-scc.yaml, tooling/charts/do500/templates/gitlab/routes.yaml
Just a couple of things to note in the PR:
- Updated apiVersion to use fully qualified path
- Uses a `ClusterRoleBinding` for gitlab-user to use the `system:openshift:scc:anyuid` role rather than creating a new system SCC which is inline with updated training and how the newest `oc adm policy add-scc-to-user ...` is doing things
- Hostname in the gitlab route has two sets of  double quotes which doesn't play well with linters and syntax highlighting.
=> Updates for Openshift >= 4.6

tooling/charts/do500/values.yaml
Reverts the default behavior back to having the ldap information auto-discovered and only requires that you set the appropriate secret name
=> Default back to have ldap info auto-discover

helm-release.yml
This adds a HelmChart CR (to work with the Helm Operator) which is a (very) temporary workaround in order to get this to deploy nicely via the applier via LodeStar.
=> Temporary workaround to deploy nicely via LodeStar

codereadyworkspaces/do500-devfile.yaml, codereadyworkspaces/stack/Dockerfile, codereadyworkspaces/stack/VERSION, tooling/charts/do500/Chart.yaml, tooling/charts/do500/templates/crd-reader.yaml, tooling/charts/do500/templates/operators/operatorgroup.yaml, tooling/charts/do500/templates/stackrox/central.yaml, tooling/charts/do500/templates/stackrox/namespace.yaml, tooling/charts/do500/templates/stackrox/secured-cluster.yaml, tooling/charts/do500/templates/wait-for-crd.yaml, tooling/charts/do500/values.yaml
add stackrox/ACS operator and installation
installs operator, central and secured cluster.
does NOT currently wire up the init bundle in stackrox, cause there is a chicken and egg with generating the api token needed. so left that for now.
=> 🫑  add stackrox 🫑

tooling/README.md, tooling/charts/do500/templates/crw/crw.yaml, tooling/charts/do500/templates/logging/clusterlogging.yaml, tooling/charts/do500/templates/logging/namespace.yaml, tooling/charts/do500/templates/wait-for-crd.yaml, tooling/charts/do500/values.yaml
fix up these errors on install. add helm hooks, fixup yaml.
```
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "ClusterLogging" in version "logging.openshift.io/v1", error validating "": error validating data: ValidationError(Subscription.spec): missing required field "name" in com.coreos.operators.v1alpha1.Subscription.spec]
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Subscription.spec): missing required field "name" in com.coreos.operators.v1alpha1.Subscription.spec
```
=> 🐟 logging install fix ups 🐟

codereadyworkspaces/stack/Dockerfile, codereadyworkspaces/stack/VERSION, codereadyworkspaces/tl112-devfile.yaml
I didn't want to create a separate container image for SRE Enablement as most of the CLIs are in common. I just added jsonnet and jsonnet bundler cli (which will be used for PrometheusRule and Grafana dashboards creation). 
I created a separate devfile though, as some paths seem to be different for now. (but I'll look to make it common also)
I named it as `tl112` but I know that's not the actual name - it is temporary for my tests :)
@eformat - what do you think? thanks!
=> 🐁 ADD - jsonnet cli to CRW stack 🐁

tooling/README.md, tooling/charts/do500/Chart.yaml, tooling/charts/do500/values.yaml
Move to start using the Red Hat GitOps Operator. Pulled in as a chart dep.
This configuration will install the cluster wide Subscription only.
Individual ArgoCD's will be configured as part of enablement.
=> 🌊 move to rh gitops operator chart 🌊

helm-release.yaml
helm-release.yaml  on `main` still holds reference to `v1.0.0` of Helm Chart. 
I've updated it to match branch to unblock testing
=> Modify version reference on helm-release.yaml to match branch

README.md, tooling/README.md, tooling/charts/tl500/values.yaml
@springdo @ckavili after further conversation around IdM group naming, we believe we'll be best off keeping it a bit more generic. Hence this PR. Let us know if you believe this will cause any sort of conflicts/issues for your side. 
Also, capitalizing a few places where PR #71 made them lower case
@jfilipcz @makirill FYI
=> remove 'tl500' prefix from IdM group

tooling/charts/tl500/values.yaml
The OpenShift Elasticsearch operator needs to be deployed at cluster scope for logging. Else you do not get kibana and es deployed when deploying logging. Frustratingly you dont even get an error in the logging oeprator pod !!
The chart template for OperatorGroups supports namespaced only.
So, for tl500, chuck this into openshift-operators namespace, which is fine (and has a cluster scoped OG) since we are not working about other Elastic stack stuff during tl500.
Working output in testing cluster
```
NAME                                            READY   STATUS      RESTARTS   AGE
cluster-logging-operator-6f79c557b9-6v74d       1/1     Running     0          25m
collector-7l4l5                                 2/2     Running     0          23m
collector-8f9bz …
```
=> 🍄 fix ES logging deployment 🍄

.github/workflows/tl500-release.yml
Once PR has been reviewed/approved, I'll create the `gh-pages` branch and setup the repo for the action to be able to publish the Helm Charts.
=> Adding GH action release to publish Helm Charts

.github/workflows/tl500-release.yml
Since we have a different DNS/URL format than standard GH Pages, this PR changes the URL to use our Labs format.
=> Correcting GH pages URL for Helm Charts

tooling/charts/tl500/values.yaml
in latest openshift 4.9.15, CRW now 2.14.0 moved into latest channel
=> 🐓 codeready 2.14.0 🐓

tooling/charts/tl500/values.yaml
sub chart dep for stackrox was stuck on do500 .. values were not getting substituted correctly because the chart is named "stackrox-chart" not "stackrox"
this fixes values substitution in dependency sub chart
=> 🦙 fix tl500 in stackrox sub chart dep 🦙

tooling/charts/tl500/templates/_helpers.tpl
This aligns with the rest of the functionality in this template file for `gitlab.ldap` definitions.
This will also allow for a `helm template` run to successfully complete (as the `lookup` functionality isn't supported with `helm template`).
=> Updating helper function to allow for a complete GitLab LDAP definition

tooling/charts/tl500/Chart.yaml, tooling/charts/tl500/values.yaml
installed tl500 chart into 4.10-rc2 cluster
removed csv starting args (just auto install latest stable channels)
CRW changed namespaces required (can't be in openshift-operators)
i will be testing tl500 tech-exercises against this env
=> 🐑 install tl500 into 4.10 cluster 🐑

tooling/charts/tl500/Chart.yaml
updates the chart dep for stackrox which adds scanner pod resource limits - defaults are:
```
scanner:
analyzer:
resources:
limits:
cpu: 500m
requests:
cpu: 100m
```
=> 🧸 stackox scanner resource limits 🧸

tooling/charts/tl500/fixed-operators-versions.yaml
This PR adds a values.yaml type of the file to keep fixed operator versions for use with Labs SRE Automation
=> Add fixed operators values file for Labs SRE Automation

tooling/charts/tl500-base/values.yaml
merging this, needed to fix TL500 course content deployment
```
failed: [bastion.w79pf.internal] (item=helm upgrade --install tl500-course-content . --namespace tl500 --create-namespace --timeout=20m) => {"ansible_loop_var": "item", "changed": true, "cmd": ["helm", "upgrade", "--install", "tl500-course-content", ".", "--namespace", "tl500", "--create-namespace", "--timeout=20m"], "delta": "0:20:23.938484", "end": "2022-05-11 00:55:19.478627", "item": "helm upgrade --install tl500-course-content . --namespace tl500 --create-namespace --timeout=20m", "msg": "non-zero return code", "rc": 1, "start": "2022-05-11 00:34:55.540143", "stderr": "Error: failed post-install: timed out waiting for the condition", "stderr_lines": ["Error: failed post-install: timed out waiting for the condition"], …
```
=> 🍒 switch pipelines to the latest channel 🍒

tooling/README.md, tooling/charts/tl500-base/templates/gitlab/deployments.yaml, tooling/charts/tl500-base/values.yaml
* Updated README to cover Gitlab integration with LDAP
* Updated root password for Gitlab;)
=> Gitlab Readme and default password update

tooling/charts/tl500-base/Chart.yaml
Gitops Operator Chart -> 0.3.9 (Removal of StartingCSV)
StackRox Operator Chart -> 0.0.5 (RBAC fix)
=> Bump versions on StackRox and Gitops operator

tooling/charts/tl500-base/Chart.yaml
upadate for latest gitops operator - 1.6.0, matches this PR
https://github.com/redhat-cop/helm-charts/pull/281
=> 🐹 argocd 2.4.7, gitops 1.6.0 🐹

tooling/charts/tl500-base/templates/tl500-rbac.yaml
Add a check for existence of `ipa` namespace before trying to create a RoleBinding for that project
=> Add a check for existence of `ipa` namespace in RBAC

tooling/charts/tl500-base/templates/tl500-rbac.yaml, tooling/charts/tl500-base/values.yaml
Parametrize IPA namespace and also make it optional to support deployments where IPA/IDM is deployed outside OpenShift, like the GLS environments.
=> Parametrize ipa namespace

tooling/charts/tl500-course-content/templates/docs/configmap.yaml, tooling/charts/tl500-course-content/templates/docs/deploy.yaml
Add explicit check for both .Values.docs and .Values.docs.config in TL500 docs deployment and config
=> Improve TL500-course-content backward compability

codereadyworkspaces/stack/Dockerfile
The tkn-linux-amd64 tar.gz filename format has been changed at https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/pipeline/latest/ so this fix is needed to keep the Dockerfile building without errors.
=> Fix the new tkn-linux-amd64.tar.gz name format

codereadyworkspaces/stack/Dockerfile
Fixed tekton install on codereadyworkspaces stack Dockerfile because the URL/filename format to extract the binary has changed:  https://mirror.openshift.com/pub/openshift-v4/clients/pipeline/latest .
Fixed go modules install on  codereadyworkspaces stack Dockerfile because 'go get' cmd has been deprecated in favour of 'go install'
=> Fix go and tekton install on codereadyworkspaces stack Dockerfile

codereadyworkspaces/stack/Dockerfile
As suggested by @eformat I have added k6 load testing tool (https://k6.io/)  to replace hey tool to perform the load test lab 5-the-deployments-strike-back/1-autoscaling step 5). k6 supports the management of insecure TLS connections needed by the TL500 GLS lab env. Once this PR merged, I will modify the deployments-strike-back/1-autoscaling step 5) lecture to add the new instructions.
=> Add k6 install on codereadyworkspaces stack Dockerfile

.github/workflows/tl500-stack-image-pr.yaml
latest tkn
https://mirror.openshift.com/pub/openshift-v4/clients/pipelines/1.10.0/tkn-linux-amd64.tar.gz
reports
$ ./tkn version
Client version: 0.30.1
on cli .. so disable this in pre-build
=> 🐰 tkn version 1.10.0 does not match 0.30.1 🐰

tooling/charts/tl500-base/values.yaml, tooling/charts/tl500-course-content/templates/image-puller.yaml
Adding image puller to the tooling to pull tl500 image beforehand in each node to fasten the initial launching devspaces process ☺️ we can possibly add other devworkspace images to the list but even just having tl500-stack on the list makes difference 🙌
=> 🐈adding image puller🐈

tooling/charts/tl500-base/Chart.yaml, tooling/charts/tl500-base/templates/_helpers.tpl, tooling/charts/tl500-base/templates/gitlab/anyuid-scc.yaml, tooling/charts/tl500-base/templates/gitlab/deployments.yaml, tooling/charts/tl500-base/templates/gitlab/imagestreams.yaml, tooling/charts/tl500-base/templates/gitlab/routes.yaml, tooling/charts/tl500-base/templates/gitlab/secrets.yaml, tooling/charts/tl500-base/templates/gitlab/serviceaccounts.yaml, tooling/charts/tl500-base/templates/gitlab/services.yaml, tooling/charts/tl500-base/templates/gitlab/volumeclaims.yaml, tooling/charts/tl500-base/values.yaml
Store Gitlab credentials in a secret to address issue #69 
The user can set the desired credentials during installation, otherwise the credentials will be generated. During upgrade, the credentials are retrieved from the secret.
Note that this fix does not attempt to address the issue when the user tries to reset the Gitlab credentials during an upgrade.
=> 🔒make gitlab credentials idempotent 🔒
