rht-labs/enablement-framework

tooling/charts/do500/templates/gitlab/deployments.yaml

Add default password and generate HTTPS URLs

---

tooling/charts/do500/templates/_helpers.tpl
tooling/charts/do500/templates/gitlab/deployments.yaml

Inject leading cn=accounts to LDAP base lookup

---

tooling/charts/do500/templates/_helpers.tpl

Let the helm chart discover the appropriate secret name

Discover secret

---

tooling/README.md

Updating docs to remove outdated note. Issue was resolved by #8

Remove outdated note in docs

---

codereadyworkspaces/stack/Dockerfile

@eformat FYI .... 
@ckavili -  you know what to do .... 😄

🐌 FIX - mikes broken docker nonsense :P  🐌

---

codereadyworkspaces/do500-devfile.yaml

use the new shiny image in stack devfile

🔫 use the new stack image 🔫

---

tooling/charts/do500/templates/user-workload-monitoring/configmap.yaml
tooling/charts/do500/values.yaml

@ckavili - as discussed earlier

🐊 ADD - user workload monitoring config 🐊

---

tooling/charts/do500/Chart.yaml
tooling/charts/do500/values.yaml

add cert utils for keycloak in new exercises

💫 Add Cert Utils 💫

---

codereadyworkspaces/do500-devfile.yaml
codereadyworkspaces/stack/Dockerfile
codereadyworkspaces/stack/VERSION

Cosign cli is added for users to create private/public keys for Image Signing module.

Add cosign

---

codereadyworkspaces/do500-devfile.yaml
codereadyworkspaces/stack/Dockerfile
codereadyworkspaces/stack/VERSION

hey cli is added for the Autoscaling section in TL500.

🐲 ADD - hey cli for load 🐲

---

codereadyworkspaces/do500-devfile.yaml

🦙 fix npm permissions 🦙

---

tooling/charts/do500/templates/crw/crw.yaml

🐙 increase default pvc size for workspaces for npm 🐙

---

tooling/charts/do500/values.yaml

update csv to latest versions for openshift 4.8.12 install

💄 newer versions for ocp 4.8.12 💄

---

do500-rbac.yaml

updated RBAC for CRD's which is needed to install argocd amongst others

🦩 updated rbac for crd's 🦩

---

tooling/charts/do500/Chart.yaml
tooling/charts/do500/templates/do500-rbac.yaml
tooling/charts/do500/values.yaml

@jfilipcz  - as discussed on the call, i've moved this in for completeness

🐉 MOVE - rbac inside the chart and url for stackrox 🐉

---

tooling/charts/do500/values.yaml

updated CSV versions to match testing cluster 4.9.9

🎃 updated versions to match  4.9.9 cluster 🎃

---

tooling/charts/do500/templates/registry/config-imageregistry.yaml
tooling/charts/do500/templates/registry/rbac.yaml

expose registry securely for image signing exercise:
https://github.com/rht-labs/tech-exercise/issues/73

🩴 expose registry 🩴

---

tooling/charts/tl500/Chart.yaml

update to latest gitops-operator chart.

🍕 gitops chart 0.2.0 🍕

---

tooling/charts/tl500/templates/tl500-rbac.yaml

🐩 monitoring rbac fails for student user 🐩

---

tooling/charts/tl500/Chart.yaml

applies this fix for central install
wait for this to merge
https://github.com/redhat-cop/helm-charts/pull/235

🥗 stackrox central fix timing issue 🥗

---

tooling/charts/tl500/templates/stackrox/configure-stackrox-job.yaml

not urgent, but no need to fix this version, use latest stack container

💎 use the latest image 💎

---

tooling/charts/tl500-base/templates/tl500-rbac.yaml

rbac file went missing during chart split

🐀 add rbac back 🐀

---

tooling/charts/tl500-base/Chart.yaml
tooling/charts/tl500-base/values.yaml

Adding tl500-teamsters app to the enablement framework deployment.
https://github.com/rht-labs/tl500-teamsters
This app can create a TEAM and fast forward them to the end of a Exercise in TL500.

🐝 add tl500-teamsters app deployment 🐝

---

tooling/charts/tl500-base/values.yaml

🍁 fix missing namespace 🍁

---

tooling/README.md

the helm chart install doco was wrong and a bit complex. tidied up.

🐞 fixup doco 🐞

---

tooling/charts/tl500-base/Chart.yaml

cc: @jfilipcz - use latest chart

🍃 latest stackrox chart 🍃

---

tooling/README.md

🦈 ADD - missing search step 🦈

---

tooling/charts/tl500-base/Chart.yaml

update to latest chart version

🪸 update gitops-operator chart 0.3. 🪸

---

tooling/charts/tl500-base/Chart.yaml

Bump gitops chart version

---

tooling/charts/tl500-course-content/templates/crw/crwv2.yaml

testing in rphds .. need to merge this quick. should be ok, as only affects 4.11

🙀 devfile v2 values file - updated after rhpds test 🙀

---

tooling/charts/tl500-base/Chart.yaml

updates redhat-cop charts
- stackrox-chart 0.0.7
- gitops-operator 0.5.1

🎉 update redhat-cop chat versions 🎉

---

tooling/README.md
tooling/charts/tl500-base/templates/gitlab/deployments.yaml
tooling/charts/tl500-base/templates/machineset-infra.yaml
tooling/charts/tl500-base/values.yaml

As per the description, just a small rework to allow node pinning for gitlab. I checked in the spec for the machineset for somewhere to keep it

🐭 ADD - node pinning for gitlab 🐭

---

.github/workflows/tl500-stack-image-publish.yaml

🐌 update base image 🐌

---

README.md

add documentation on how to create a basic setup, to make it easier for others (and myself :-D) to contribute to and extend the TL-500 infrastructure and exercises

add setup doc
